# Generated by Django 5.2.3 on 2026-04-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPAGe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmms', to='OPAGe.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RMMKeyPillarWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('key_pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_weights', to='OPAGe.keypillar')),
                ('rmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kp_weights', to='OPAGe.rmm')),
            ],
            options={
                'unique_together': {('rmm', 'key_pillar')},
            },
        ),
    ]
