# Generated by Django 5.2.3 on 2026-04-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPAGe', '0002_keypillar_rmm_rmmkeypillarweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='raw_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
