# Generated by Django 5.2.3 on 2026-04-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPAGe', '0003_alter_indicator_raw_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='normalized_value',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='raw_value',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='val_max',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='val_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.FloatField()),
                ('normalized_value', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='OPAGe.indicator')),
            ],
        ),
    ]
