# Generated by Django 6.0.4 on 2026-04-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mpage_dimension',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KeyPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('pillar_type', models.CharField(choices=[('governance', 'Gouvernance'), ('organizational', 'Organisationnel'), ('legal', 'Juridique'), ('technical', 'Technique'), ('human', 'Humain'), ('financial', 'Financier')], max_length=50)),
                ('icon', models.CharField(blank=True, default='shield', max_length=50)),
            ],
            options={
                'db_table': 'mpage_keypillar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('associated_risk_id', models.IntegerField(help_text='ID of the Risk in O-PAGe (OPAGe_risk table)')),
                ('associated_risk_name', models.CharField(blank=True, help_text='Cached name of the associated risk from O-PAGe', max_length=255)),
            ],
            options={
                'db_table': 'mpage_rmm',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminee')], default='draft', max_length=20)),
                ('launch_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpage_campaign',
                'ordering': ['-launch_date'],
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='mpage.dimension')),
            ],
            options={
                'db_table': 'mpage_factor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GPMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpm_results', to='mpage.campaign')),
            ],
            options={
                'db_table': 'mpage_gpm_result',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mpage.factor')),
            ],
            options={
                'db_table': 'mpage_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='dimension',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='mpage.keypillar'),
        ),
        migrations.CreateModel(
            name='ReadinessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_levels', to='mpage.campaign')),
                ('key_pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpage.keypillar')),
                ('rmm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpage.riskmitigationmechanism')),
            ],
            options={
                'db_table': 'mpage_readiness_level',
            },
        ),
        migrations.CreateModel(
            name='ItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Score from 1 (very low) to 5 (very high)')),
                ('comment', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mpage.campaign')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mpage.item')),
            ],
            options={
                'db_table': 'mpage_item_response',
                'unique_together': {('campaign', 'item')},
            },
        ),
        migrations.CreateModel(
            name='RMCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.IntegerField(help_text='O-PAGe Risk ID')),
                ('risk_name', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmc_results', to='mpage.campaign')),
            ],
            options={
                'db_table': 'mpage_rmc_result',
                'unique_together': {('campaign', 'risk_id')},
            },
        ),
        migrations.CreateModel(
            name='RMMCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmmc_results', to='mpage.campaign')),
                ('rmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpage.riskmitigationmechanism')),
            ],
            options={
                'db_table': 'mpage_rmmc_result',
                'unique_together': {('campaign', 'rmm')},
            },
        ),
        migrations.CreateModel(
            name='RMMKeyPillarWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('key_pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_weights', to='mpage.keypillar')),
                ('rmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kp_weights', to='mpage.riskmitigationmechanism')),
            ],
            options={
                'db_table': 'mpage_rmm_kp_weight',
                'unique_together': {('rmm', 'key_pillar')},
            },
        ),
    ]
