# Generated by Django 6.0.4 on 2026-04-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresponse',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Raw responses from the Excel import (e.g. Resp1, Resp2...)', null=True),
        ),
        migrations.AlterField(
            model_name='itemresponse',
            name='response',
            field=models.FloatField(default=0.0, help_text='Calculated average score from 1 to 5'),
        ),
    ]
