# Generated by Django 6.0.4 on 2026-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpage', '0002_itemresponse_raw_data_alter_itemresponse_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypillar',
            name='pillar_type',
            field=models.CharField(max_length=255),
        ),
    ]
