# Generated by Django 6.0.4 on 2026-05-10 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpage', '0003_alter_keypillar_pillar_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPageIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ipage_indicator',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IPageMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_active', models.BooleanField(default=False)),
                ('default_level', models.FloatField(default=0.5)),
            ],
            options={
                'db_table': 'ipage_mechanism',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IPageScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ipage_scenario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IPageSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('risk_id', models.IntegerField(help_text='O-PAGe Risk ID')),
                ('risk_name', models.CharField(blank=True, max_length=255)),
                ('risk_score', models.FloatField(default=0.0, help_text='Initial risk score from O-PAGe')),
                ('method', models.CharField(choices=[('linear', 'Linear Propagation'), ('monte_carlo', 'Simplified Monte Carlo'), ('diffusion', 'Diffusion Model')], default='linear', max_length=20)),
                ('confidence', models.CharField(choices=[('low', 'Low (25%)'), ('medium', 'Medium (50%)'), ('high', 'High (75%)')], default='medium', max_length=20)),
                ('horizon', models.CharField(choices=[('6m', '6 mois'), ('12m', '12 mois'), ('18m', '18 mois'), ('24m', '24 mois')], default='12m', max_length=10)),
                ('iterations', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score_after', models.FloatField(default=0.0)),
                ('reduction_absolute', models.FloatField(default=0.0)),
                ('reduction_relative', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_level_before', models.CharField(blank=True, max_length=20)),
                ('risk_level_after', models.CharField(blank=True, max_length=20)),
                ('computed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpage.ipagescenario')),
            ],
            options={
                'db_table': 'ipage_simulation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPageMechanismEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0, help_text='Impact coefficient from -1.0 to +1.0')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanism_effects', to='mpage.ipageindicator')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='mpage.ipagemechanism')),
            ],
            options={
                'db_table': 'ipage_mechanism_effect',
                'unique_together': {('mechanism', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='IPageScenarioMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('level', models.FloatField(default=0.5, help_text='Deployment level 0.0 to 1.0')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_uses', to='mpage.ipagemechanism')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_mechanisms', to='mpage.ipagescenario')),
            ],
            options={
                'db_table': 'ipage_scenario_mechanism',
                'unique_together': {('scenario', 'mechanism')},
            },
        ),
        migrations.CreateModel(
            name='IPageSimulationMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('level', models.FloatField(default=0.5)),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpage.ipagemechanism')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_mechanisms', to='mpage.ipagesimulation')),
            ],
            options={
                'db_table': 'ipage_simulation_mechanism',
                'unique_together': {('simulation', 'mechanism')},
            },
        ),
        migrations.CreateModel(
            name='IPageSimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_value', models.FloatField(default=0.0, help_text='Averaged impact on this indicator')),
                ('reduction_pct', models.FloatField(default=0.0, help_text='Percentage reduction')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpage.ipageindicator')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mpage.ipagesimulation')),
            ],
            options={
                'db_table': 'ipage_simulation_result',
                'unique_together': {('simulation', 'indicator')},
            },
        ),
    ]
