# Generated by Django 6.0.5 on 2026-05-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpage', '0004_ipageindicator_ipagemechanism_ipagescenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Administrator',
                'verbose_name_plural': 'System Administrators',
                'db_table': 'system_admin',
            },
        ),
    ]
