import React, { useState, useEffect, useCallback } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { opageApi, ipageApi, OPageRisk, IPageScenario, IPageMechanism, IPageIndicator, IPageSimulationRunResponse } from '../services/api';
import { useAuth } from '../context/AuthContext';

const steps = ['Parameters', 'Simulation', 'Impact matrix', 'Results'];

const defaultRisks = [
  {
    id: 1,
    name: 'R-05 Algorithmic discrimination',
    description:
      'Risk linked to discriminatory decisions generated by an algorithm for access to benefits.',
    score: 0.78,
    level: 'HIGH',
  },
  {
    id: 2,
    name: 'R-02 Regulatory non-compliance',
    description:
      'Risk of failing to comply with the legal and regulatory obligations of the algorithmic system.',
    score: 0.52,
    level: 'MODERATE',
  },
];

const defaultScenarios = [
  {
    id: 1,
    name: 'Governance & technical strengthening',
    description:
      'Scenario combining governance controls and technical actions to reduce risk.',
  },
  {
    id: 2,
    name: 'Compliance-focused approach',
    description:
      'Scenario centered on regulatory compliance and formal audits.',
  },
];

const defaultMethods = ['Linear propagation', 'Simplified Monte Carlo', 'Diffusion model'];
const defaultConfidences = ['Low (25%)', 'Medium (50%)', 'High (75%)'];
const defaultHorizons = ['6 months', '12 months', '18 months', '24 months'];
const defaultPeriods = ['Monthly', 'Quarterly'];

const indicators = [
  'Error rate',
  'Algorithmic bias',
  'Transparency',
  'Number of complaints',
  'Processing time',
  'Regulatory compliance',
];

const defaultMechanisms = [
  {
    id: 1,
    name: 'Regular algorithmic audit',
    description: 'Perform periodic audits of algorithms and the data used.',
    active: true,
    level: 0.8,
    effects: {
      'Error rate': 0.8,
      'Algorithmic bias': 0.7,
      Transparency: 0.6,
      'Number of complaints': 0.4,
      'Processing time': 0.3,
      'Regulatory compliance': 0.6,
    },
  },
  {
    id: 2,
    name: 'Technical data improvements',
    description: 'Improve data quality, diversity and governance.',
    active: true,
    level: 0.6,
    effects: {
      'Error rate': 0.7,
      'Algorithmic bias': 0.5,
      Transparency: 0.2,
      'Number of complaints': 0.1,
      'Processing time': 0.6,
      'Regulatory compliance': 0.3,
    },
  },
  {
    id: 3,
    name: 'Transparency and explainability',
    description: 'Implement transparency and explainability practices.',
    active: false,
    level: 0.7,
    effects: {
      'Error rate': 0.2,
      'Algorithmic bias': 0.6,
      Transparency: 0.8,
      'Number of complaints': 0.3,
      'Processing time': 0.1,
      'Regulatory compliance': 0.4,
    },
  },
  {
    id: 4,
    name: 'Training & awareness',
    description: 'Ongoing team training and risk awareness.',
    active: true,
    level: 0.5,
    effects: {
      'Error rate': 0.3,
      'Algorithmic bias': 0.6,
      Transparency: 0.4,
      'Number of complaints': 0.2,
      'Processing time': 0.1,
      'Regulatory compliance': 0.2,
    },
  },
  {
    id: 5,
    name: 'Data governance',
    description: 'Establish robust governance for data and models.',
    active: false,
    level: 0.6,
    effects: {
      'Error rate': 0.6,
      'Algorithmic bias': 0.4,
      Transparency: 0.3,
      'Number of complaints': 0.3,
      'Processing time': 0.2,
      'Regulatory compliance': 0.6,
    },
  },
  {
    id: 6,
    name: 'Regulation & compliance',
    description: 'Align with applicable standards and regulations.',
    active: false,
    level: 0.0,
    effects: {
      'Error rate': 0.1,
      'Algorithmic bias': 0.2,
      Transparency: 0.1,
      'Number of complaints': 0.0,
      'Processing time': 0.0,
      'Regulatory compliance': 0.4,
    },
  },
];

interface ImpactSimulationForm {
  riskId: number;
  scenarioId: number;
  horizon: string;
  period: string;
  indicatorWeightMode: 'existing' | 'custom';
  method: string;
  confidence: string;
  iterations: number;
}

interface MechanismState {
  id: number;
  name: string;
  description: string;
  active: boolean;
  level: number;
  effects: Record<string, number>;
}

export function ImpactSimulation() {
  const { user } = useAuth();
  const isReadOnly = user?.role === 'observateur';
  const [currentStep, setCurrentStep] = useState<number>(0);
  const [loading, setLoading] = useState(true);
  const [risks, setRisks] = useState<OPageRisk[]>([]);
  const [scenarios, setScenarios] = useState<IPageScenario[]>([]);
  const [apiMechanisms, setApiMechanisms] = useState<IPageMechanism[]>([]);
  const [apiIndicators, setApiIndicators] = useState<IPageIndicator[]>([]);
  const [simulationResult, setSimulationResult] = useState<IPageSimulationRunResponse | null>(null);

  // Create-scenario modal state
  const [showCreateScenario, setShowCreateScenario] = useState(false);
  const [newScenarioName, setNewScenarioName] = useState('');
  const [newScenarioDesc, setNewScenarioDesc] = useState('');
  const [creatingScenario, setCreatingScenario] = useState(false);

  const [form, setForm] = useState<ImpactSimulationForm>({
    riskId: 1,
    scenarioId: 1,
    horizon: defaultHorizons[1],
    period: defaultPeriods[0],
    indicatorWeightMode: 'existing',
    method: defaultMethods[0],
    confidence: defaultConfidences[1],
    iterations: 1000,
  });

  const [mechanisms, setMechanisms] = useState<MechanismState[]>([]);

  const loadScenarios = useCallback(async () => {
    try {
      const sRes = await ipageApi.scenarios();
      setScenarios(sRes);
      return sRes;
    } catch (err) {
      console.error('Error loading scenarios', err);
      return [];
    }
  }, []);



  useEffect(() => {
    async function loadData() {
      try {
        const [rRes, sRes, mRes, iRes] = await Promise.all([
          opageApi.risks(),
          ipageApi.scenarios(),
          ipageApi.mechanisms(),
          ipageApi.indicators()
        ]);
        setRisks(rRes);
        setScenarios(sRes);
        setApiMechanisms(mRes);
        setApiIndicators(iRes);
        
        if (rRes.length > 0) setForm(f => ({ ...f, riskId: rRes[0].id }));
        if (sRes.length > 0) setForm(f => ({ ...f, scenarioId: sRes[0].id }));

        const mechState = mRes.map(m => {
          const effectsRecord: Record<string, number> = {};
          m.effects.forEach(e => { effectsRecord[e.indicator_name] = e.value; });
          return {
            id: m.id,
            name: m.name,
            description: m.description,
            active: m.default_active,
            level: m.default_level,
            effects: effectsRecord
          };
        });
        setMechanisms(mechState);
      } catch (err) {
        console.error('Error loading simulation data', err);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, []);

  const selectedRisk = risks.find((risk) => risk.id === form.riskId);
  const selectedScenario = scenarios.find((scenario) => scenario.id === form.scenarioId);

  const activeMechanisms = mechanisms.filter((mechanism) => mechanism.active);
  const activeCount = activeMechanisms.length;
  const averageDeployment = activeCount > 0 ? activeMechanisms.reduce((sum, item) => sum + item.level, 0) / activeCount : 0;
  const effectivenessScore = activeCount > 0 ? activeMechanisms.reduce((sum, item) => sum + getEffectiveness(item.level), 0) / activeCount : 0;
  const distribution = {
    high: activeMechanisms.filter((item) => getEffectiveness(item.level) === 3).length,
    medium: activeMechanisms.filter((item) => getEffectiveness(item.level) === 2).length,
    low: activeMechanisms.filter((item) => getEffectiveness(item.level) === 1).length,
  };

  const allActiveCellValues = activeMechanisms.flatMap((mechanism) => apiIndicators.map((indicator) => mechanism.effects[indicator.name] ?? 0));
  const impactedIndicatorsCount = new Set(
    activeMechanisms.flatMap((mechanism) => apiIndicators.map(i => i.name).filter((indicator) => (mechanism.effects[indicator] ?? 0) !== 0)),
  ).size;
  const matrixAverageImpact = allActiveCellValues.length > 0 ? allActiveCellValues.reduce((sum, value) => sum + value, 0) / allActiveCellValues.length : 0;
  const matrixMaxImpact = allActiveCellValues.length > 0 ? Math.max(...allActiveCellValues) : 0;
  const matrixMinImpact = allActiveCellValues.length > 0 ? Math.min(...allActiveCellValues) : 0;
  const matrixDistribution = {
    strong: allActiveCellValues.filter((value) => value >= 0.7).length,
    moderate: allActiveCellValues.filter((value) => value >= 0.3 && value < 0.7).length,
    weak: allActiveCellValues.filter((value) => value > 0 && value < 0.3).length,
    neutral: allActiveCellValues.filter((value) => value === 0).length,
    negative: allActiveCellValues.filter((value) => value < 0).length,
  };

  function getEffectiveness(level: number) {
    if (level >= 0.7) return 3;
    if (level >= 0.4) return 2;
    return 1;
  }

  function getEffectivenessLabel(level: number) {
    const value = getEffectiveness(level);
    return value === 3 ? 'High' : value === 2 ? 'Medium' : 'Low';
  }

  function getEffectivenessClass(level: number) {
    const value = getEffectiveness(level);
    return value === 3 ? 'bg-emerald-100 text-emerald-700' : value === 2 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-700';
  }

  function getImpactCategory(value: number) {
    if (value >= 0.7) return { label: 'Strong impact', className: 'bg-emerald-100 text-emerald-700' };
    if (value >= 0.3) return { label: 'Moderate impact', className: 'bg-lime-100 text-lime-800' };
    if (value > 0) return { label: 'Low impact', className: 'bg-slate-100 text-slate-700' };
    if (value === 0) return { label: 'Neutral', className: 'bg-slate-100 text-slate-700' };
    return { label: 'Negative impact', className: 'bg-red-100 text-red-700' };
  }

  const getCellClasses = (value: number) => {
    if (value >= 0.7) return 'bg-emerald-500 text-white';
    if (value >= 0.3) return 'bg-emerald-200 text-slate-900';
    if (value > 0) return 'bg-emerald-100 text-slate-900';
    if (value === 0) return 'bg-slate-100 text-slate-700';
    return 'bg-red-100 text-red-700';
  };

  const [editingCell, setEditingCell] = useState<{ rmmId: number; indicator: string } | null>(null);

  const updateMechanism = (id: number, changes: Partial<MechanismState>) => {
    if (isReadOnly) return;
    setMechanisms((prev) => prev.map((item) => (item.id === id ? { ...item, ...changes } : item)));
  };

  const updateMechanismEffect = (id: number, indicator: string, value: number) => {
    if (isReadOnly) return;
    setMechanisms((prev) =>
      prev.map((item) =>
        item.id === id
          ? {
              ...item,
              effects: {
                ...item.effects,
                [indicator]: Number(value?.toFixed(2)),
              },
            }
          : item,
      ),
    );
  };

  const resetMatrix = () => {
    setMechanisms(prev => prev.map(item => {
      const defaultItem = apiMechanisms.find(m => m.id === item.id);
      if (defaultItem) {
        const effectsRecord: Record<string, number> = {};
        defaultItem.effects.forEach(e => { effectsRecord[e.indicator_name] = e.value; });
        return { ...item, effects: effectsRecord };
      }
      return item;
    }));
  };

  const initialRiskScore = selectedRisk?.scores?.[0]?.score ?? 0.78;
  const riskScoreInitial = simulationResult?.simulation.risk_score ?? initialRiskScore;
  const riskScoreAfter = simulationResult?.simulation.risk_score_after ?? Math.max(0, riskScoreInitial - Math.min(0.35, matrixAverageImpact * 0.25));
  const reductionAbsolute = -(simulationResult?.simulation.reduction_absolute ?? Math.abs(+(riskScoreAfter - riskScoreInitial)?.toFixed(2)));
  const reductionRelative = simulationResult?.simulation.reduction_relative ?? (riskScoreInitial > 0 ? +((Math.abs(reductionAbsolute) / riskScoreInitial) * 100)?.toFixed(0) : 0);
  const riskLevelLabel = (score: number) => (score >= 0.75 ? 'HIGH' : score >= 0.4 ? 'MODERATE' : 'LOW');
  const riskLevelClass = (score: number) =>
    score >= 0.75
      ? 'bg-red-100 text-red-700'
      : score >= 0.4
      ? 'bg-amber-100 text-amber-800'
      : 'bg-emerald-100 text-emerald-700';

  const actualRiskTrend = simulationResult ? simulationResult.before_trend : [
    { label: 'Initial (t0)', value: riskScoreInitial },
    { label: '3 months (t+1)', value: Math.max(0, riskScoreInitial - 0.07) },
    { label: '6 months (t+2)', value: Math.max(0, riskScoreInitial - 0.14) },
    { label: '12 months (t+3)', value: Math.max(0, riskScoreInitial - 0.18) },
  ];

  const afterRiskTrend = simulationResult ? simulationResult.after_trend : [
    { label: 'Initial (t0)', value: riskScoreAfter },
    { label: '3 months (t+1)', value: Math.max(0, riskScoreAfter - 0.04) },
    { label: '6 months (t+2)', value: Math.max(0, riskScoreAfter - 0.07) },
    { label: '12 months (t+3)', value: Math.max(0, riskScoreAfter - 0.10) },
  ];

  const riskTrendValues = [...actualRiskTrend.map((item) => item.value), ...afterRiskTrend.map((item) => item.value)];
  const riskTrendMin = Math.min(...riskTrendValues, 0);
  const riskTrendMax = Math.max(...riskTrendValues, 1);
  const riskTrendRange = riskTrendMax - riskTrendMin || 1;
  const riskTrendPath = (trend: { label: string; value: number }[]) =>
    trend
      .map((point, index) => {
        const x = 40 + index * 120;
        const y = 210 - ((point.value - riskTrendMin) / riskTrendRange) * 150;
        return `${index === 0 ? 'M' : 'L'} ${x} ${y}`;
      })
      .join(' ');

  const actualRiskTrendPath = riskTrendPath(actualRiskTrend);
  const afterRiskTrendPath = riskTrendPath(afterRiskTrend);

  const impactCounts = {
    improved: matrixDistribution.strong + matrixDistribution.moderate + matrixDistribution.weak,
    stable: matrixDistribution.neutral,
    degraded: matrixDistribution.negative,
  };

  const indicatorImpactData = simulationResult ? simulationResult.indicator_results.map(r => ({ indicator: r.indicator, value: r.reduction_pct })) : apiIndicators.map(indicatorObj => { const indicator = indicatorObj.name; const value = activeMechanisms.length ? activeMechanisms.reduce((sum, mechanism) => sum + (mechanism.effects[indicator] ?? 0), 0) / activeMechanisms.length : 0; return { indicator, value: Math.round(value * 100) }; });

  const contributionData = activeMechanisms
    .map((mechanism) => ({ name: mechanism.name, value: Math.round(mechanism.level * 100) }))
    .sort((a, b) => b.value - a.value);

  const scenarioComparisonData = simulationResult ? simulationResult.scenario_comparison : [];

  const exportPDF = () => {
    if (!simulationResult) return;
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text(`I-PAGe Simulation Report`, 14, 20);
    doc.setFontSize(12);
    doc.text(`Risk: ${selectedRisk?.name}`, 14, 30);
    doc.text(`Scenario: ${selectedScenario?.name}`, 14, 38);
    
    doc.text(`Initial risk score: ${riskScoreInitial?.toFixed(2)}`, 14, 50);
    doc.text(`Post-mitigation score: ${riskScoreAfter?.toFixed(2)}`, 14, 58);
    doc.text(`Reduction: ${Math.abs(reductionRelative)}%`, 14, 66);
    
    autoTable(doc, {
      startY: 75,
      head: [['Mechanism', 'Deployment', 'Active']],
      body: mechanisms.filter(m => m.active).map(m => [m.name, m.level?.toFixed(2), 'Yes']),
    });
    
    autoTable(doc, {
      head: [['Indicator', 'Reduction (%)']],
      body: simulationResult.indicator_results.map(r => [r.indicator, `${r.reduction_pct}%`]),
    });
    
    doc.save(`Simulation_IPAGe_${simulationResult.simulation.id}.pdf`);
  };

  const exportCSV = () => {
    if (!simulationResult) return;
    const headers = ['Indicator', 'Impact value', 'Reduction (%)'];
    const rows = simulationResult.indicator_results.map(r => [r.indicator, r.impact_value.toFixed(4), r.reduction_pct.toFixed(2)]);
    
    const csvContent = "data:text/csv;charset=utf-8," + [headers.join(','), ...rows.map(e => e.join(','))].join("\n");
      
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Simulation_IPAGe_${simulationResult.simulation.id}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleFieldChange = (field: keyof ImpactSimulationForm, value: string | number) => {
    if (isReadOnly) return;
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handleCreateScenario = async () => {
    if (!newScenarioName.trim()) return;
    setCreatingScenario(true);
    try {
      const created = await ipageApi.createScenario({
        name: newScenarioName.trim(),
        description: newScenarioDesc.trim(),
      });
      await loadScenarios();
      setForm(f => ({ ...f, scenarioId: created.id }));
      setShowCreateScenario(false);
      setNewScenarioName('');
      setNewScenarioDesc('');
    } catch (err) {
      console.error('Error creating scenario', err);
      alert('Error creating scenario');
    } finally {
      setCreatingScenario(false);
    }
  };


  const goNext = async () => {
    if (isReadOnly && currentStep === 2) {
      setCurrentStep(prev => prev + 1);
      return;
    }
    if (currentStep === 2) {
      try {
        const methodMap: Record<string, string> = {
          'Linear propagation': 'linear',
          'Simplified Monte Carlo': 'monte_carlo',
          'Diffusion model': 'diffusion'
        };
        const confMap: Record<string, string> = {
          'Low (25%)': 'low',
          'Medium (50%)': 'medium',
          'High (75%)': 'high'
        };
        const horizonMap: Record<string, string> = {
          '6 months': '6m', '12 months': '12m', '18 months': '18m', '24 months': '24m'
        };
        
        const sim = await ipageApi.createSimulation({
          risk_id: form.riskId,
          risk_score: selectedRisk?.scores?.[0]?.score ?? 0,
          scenario: scenarios.length > 0 ? form.scenarioId : null,
          method: methodMap[form.method] || 'linear',
          confidence: confMap[form.confidence] || 'medium',
          horizon: horizonMap[form.horizon] || '12m',
          iterations: form.iterations,
          mechanisms: mechanisms.map(m => ({
            mechanism_id: m.id,
            active: m.active,
            level: m.level
          }))
        });
        const res = await ipageApi.runSimulation(sim.id);
        setSimulationResult(res);
        setCurrentStep(prev => prev + 1);
      } catch (err: any) {
        console.error('Error running simulation', err);
        alert('Error running simulation: ' + (err?.message || err));
      }
    } else if (currentStep < steps.length - 1) {
      setCurrentStep((prev) => prev + 1);
    }
  };

  const goBack = () => {
    if (currentStep > 0) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  if (loading) return <div className="p-8 flex items-center justify-center min-h-[60vh]">Loading data...</div>;

  return (
    <div className="p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-semibold text-gray-900">I-PAGe Impact Simulation</h1>
        <p className="text-gray-600 mt-2">
          Configure your parameters and simulate the impact of mitigation mechanisms on your risks.
        </p>
      </div>

      <div className="mb-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {steps.map((step, index) => (
            <div key={step} className="flex items-start gap-4 rounded-3xl border border-slate-200 bg-slate-50 p-4">
              <div
                className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-semibold ${
                  index === currentStep ? 'bg-blue-600 text-white' : 'bg-white text-slate-500 shadow-sm'
                }`}
              >
                {index + 1}
              </div>
              <div>
                <p className="text-sm font-semibold text-gray-900">{step}</p>
                <p className="text-sm text-slate-500">{index === 0 ? 'Set parameters' : index === 1 ? 'Select scenario' : index === 2 ? 'View matrix' : 'Review results'}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        {currentStep === 0 && (
          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">Simulation settings</h2>
              <p className="text-gray-600 mt-1">Define the full simulation context before moving to the next step.</p>
            </div>
            <div className="grid gap-6 xl:grid-cols-2">

              <div className="space-y-5 rounded-3xl border border-slate-200 bg-slate-50 p-6">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Risk selection</p>
                    <p className="text-sm text-slate-500">Choose the risk that the simulation covers.</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-600">Risk</label>
                    <select
                      value={form.riskId}
                      onChange={(e: React.ChangeEvent<HTMLSelectElement>) => handleFieldChange('riskId', Number(e.target.value))}
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                    >
                      {risks.map((risk) => (
                        <option key={risk.id} value={risk.id}>{risk.name}</option>
                      ))}
                    </select>
                  </div>
                  <div className="rounded-3xl border border-slate-200 bg-white p-4">
                    <p className="text-sm font-semibold text-gray-900">{selectedRisk?.name}</p>
                    <p className="text-sm text-slate-600 mt-2">{selectedRisk?.description}</p>
                    <div className="mt-4 flex flex-wrap items-center gap-2 text-sm">
                      {(() => {
                        const riskCategory = selectedRisk?.scores?.[0]?.category ?? 'N/A';
                        const categoryColorClass = riskCategory === 'CRITICAL' ? 'bg-purple-100 text-purple-700'
                          : riskCategory === 'HIGH' ? 'bg-red-100 text-red-700'
                          : riskCategory === 'MODERATE' ? 'bg-amber-100 text-amber-800'
                          : riskCategory === 'LOW' ? 'bg-emerald-100 text-emerald-700'
                          : 'bg-slate-100 text-slate-700';
                        return <span className={`rounded-full px-3 py-1 ${categoryColorClass}`}>{riskCategory}</span>;
                      })()}
                      <span className="rounded-full bg-slate-100 px-3 py-1 text-slate-700">Score {selectedRisk?.scores?.[0]?.score?.toFixed(2) ?? '—'}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-5 rounded-3xl border border-slate-200 bg-slate-50 p-6">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Simulation scenario</p>
                    <p className="text-sm text-slate-500">Preconfigure a mitigation strategy.</p>
                  </div>
                  {!isReadOnly && <button
                    type="button"
                    onClick={() => setShowCreateScenario(true)}
                    className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-100"
                  >
                    + New scenario
                  </button>}
                </div>
                <div className="space-y-4">
                  <label className="block text-sm font-medium text-slate-600">Scenario</label>
                  <select
                    value={form.scenarioId}
                    onChange={(e: React.ChangeEvent<HTMLSelectElement>) => handleFieldChange('scenarioId', Number(e.target.value))}
                    className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                  >
                    {scenarios.map((scenario) => (
                      <option key={scenario.id} value={scenario.id}>{scenario.name}</option>
                    ))}
                  </select>
                  <div className="rounded-3xl border border-slate-200 bg-white p-4">
                    <p className="text-sm font-semibold text-gray-900">{selectedScenario?.name}</p>
                    <p className="text-sm text-slate-600 mt-2">{selectedScenario?.description}</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="grid gap-6 xl:grid-cols-2">
              <div className="space-y-5 rounded-3xl border border-slate-200 bg-slate-50 p-6">
                <div>
                  <p className="text-sm font-semibold text-slate-900">Simulation horizon</p>
                  <p className="text-sm text-slate-500">Define the duration and update frequency.</p>
                </div>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-600">Duration</label>
                    <select
                      value={form.horizon}
                      onChange={(e: React.ChangeEvent<HTMLSelectElement>) => handleFieldChange('horizon', e.target.value)}
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                    >
                      {defaultHorizons.map((horizon) => (
                        <option key={horizon} value={horizon}>{horizon}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-600">Update frequency</label>
                    <select
                      value={form.period}
                      onChange={(e: React.ChangeEvent<HTMLSelectElement>) => handleFieldChange('period', e.target.value)}
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                    >
                      {defaultPeriods.map((period) => (
                        <option key={period} value={period}>{period}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>

              <div className="space-y-5 rounded-3xl border border-slate-200 bg-slate-50 p-6">
                <div>
                  <p className="text-sm font-semibold text-slate-900">Indicator weighting</p>
                  <p className="text-sm text-slate-500">Control the importance of indicators in the simulation.</p>
                </div>
                <div className="space-y-3 rounded-3xl border border-slate-200 bg-white p-4">
                  <label className="flex items-center gap-3 text-sm text-slate-700">
                    <input
                      type="radio"
                      name="indicatorWeightMode"
                      checked={form.indicatorWeightMode === 'existing'}
                      onChange={() => handleFieldChange('indicatorWeightMode', 'existing')}
                      className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                    />
                    Use existing weights
                  </label>
                  <label className="flex items-center gap-3 text-sm text-slate-700">
                    <input
                      type="radio"
                      name="indicatorWeightMode"
                      checked={form.indicatorWeightMode === 'custom'}
                      onChange={() => handleFieldChange('indicatorWeightMode', 'custom')}
                      className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                    />
                    Customize weights
                  </label>
                </div>
                {form.indicatorWeightMode === 'custom' && (
                  <div className="rounded-3xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-700">
                    Advanced customization is active. You can adjust indicator weights later.
                  </div>
                )}
              </div>

              <div className="space-y-5 rounded-3xl border border-slate-200 bg-slate-50 p-6">
                <div>
                  <p className="text-sm font-semibold text-slate-900">Advanced options</p>
                  <p className="text-sm text-slate-500">Refine the simulation with expert parameters.</p>
                </div>
                <div className="space-y-4 rounded-3xl border border-slate-200 bg-white p-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-600">Simulation method</label>
                    <select
                      value={form.method}
                      onChange={(e: React.ChangeEvent<HTMLSelectElement>) => handleFieldChange('method', e.target.value)}
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                    >
                      {defaultMethods.map((method) => (
                        <option key={method} value={method}>{method}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-600">Confidence level</label>
                    <select
                      value={form.confidence}
                      onChange={(e: React.ChangeEvent<HTMLSelectElement>) => handleFieldChange('confidence', e.target.value)}
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                    >
                      {defaultConfidences.map((confidence) => (
                        <option key={confidence} value={confidence}>{confidence}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-600">Number of iterations</label>
                    <input
                      type="number"
                      value={form.iterations}
                      min={100}
                      onChange={(e: React.ChangeEvent<HTMLInputElement>) => handleFieldChange('iterations', Number(e.target.value))}
                      className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {currentStep === 1 && (
          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">Simulation</h2>
              <p className="text-gray-600 mt-1">Choose mitigation mechanisms and set their deployment level.</p>
            </div>

            <div className="grid gap-6 xl:grid-cols-[2fr_1fr]">
              <div className="space-y-6 rounded-3xl border border-slate-200 bg-slate-50 p-6">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Mechanism list</p>
                    <p className="text-sm text-slate-500">Enable mechanisms and set their deployment level.</p>
                  </div>
                  <div className="rounded-2xl bg-slate-100 px-3 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-700">
                    {activeCount}/{mechanisms.length} active
                  </div>
                </div>

                <div className="space-y-4">
                  {mechanisms.map((mechanism) => (
                    <div key={mechanism.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                        <div className="min-w-0">
                          <p className="text-sm font-semibold text-slate-900">{mechanism.name}</p>
                          <p className="text-sm text-slate-500 mt-1">{mechanism.description}</p>
                        </div>
                        <div className="flex items-center gap-3">
                          <label className="inline-flex cursor-pointer items-center gap-2 text-sm font-medium text-slate-700">
                            <input
                              type="checkbox"
                              checked={mechanism.active}
                              onChange={(e) => updateMechanism(mechanism.id, { active: e.target.checked })}
                              disabled={isReadOnly}
                              className="h-5 w-5 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                            />
                            Active
                          </label>
                        </div>
                      </div>

                      <div className="mt-5 grid gap-4">
                        <div className="flex items-center justify-between gap-4 text-sm text-slate-700">
                          <span>Deployment level</span>
                          <span className="font-semibold text-slate-900">{mechanism.level?.toFixed(2)}</span>
                        </div>
                        <input
                          type="range"
                          min={0}
                          max={1}
                          step={0.05}
                          value={mechanism.level}
                          disabled={isReadOnly || !mechanism.active}
                          onChange={(e) => updateMechanism(mechanism.id, { level: Number(e.target.value) })}
                          className="w-full accent-blue-600"
                        />
                        <div className="flex items-center justify-between gap-3 text-sm">
                          <span className="text-slate-500">0 = not deployed</span>
                          <span className="text-slate-500">0.5 = partial</span>
                          <span className="text-slate-500">1 = full</span>
                        </div>
                        <div className="flex items-center justify-between gap-4 text-sm">
                          <span className="font-semibold">Estimated effectiveness</span>
                          <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${getEffectivenessClass(mechanism.level)}`}>
                            {getEffectivenessLabel(mechanism.level)} ({mechanism.level?.toFixed(2)})
                          </span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

              </div>

              <aside className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <div>
                  <p className="text-sm font-semibold text-slate-900">Selection summary</p>
                  <div className="mt-5 space-y-4 text-sm text-slate-600">
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Active mechanisms</p>
                      <p className="mt-2 text-3xl font-semibold text-blue-600">{activeCount} / {mechanisms.length}</p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Average deployment level</p>
                      <p className="mt-2 text-3xl font-semibold text-blue-600">{averageDeployment?.toFixed(2)} / 1.00</p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Expected overall effectiveness</p>
                      <p className="mt-2 text-3xl font-semibold text-emerald-700">{effectivenessScore?.toFixed(2)}</p>
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-4">
                  <p className="text-sm font-semibold text-slate-900">Level distribution</p>
                  <div className="mt-4 space-y-3 text-sm text-slate-700">
                    <div className="flex items-center justify-between rounded-2xl bg-white px-4 py-3">
                      <span>High</span>
                      <span>{distribution.high} mechanism{distribution.high > 1 ? 's' : ''}</span>
                    </div>
                    <div className="flex items-center justify-between rounded-2xl bg-white px-4 py-3">
                      <span>Medium</span>
                      <span>{distribution.medium} mechanism{distribution.medium > 1 ? 's' : ''}</span>
                    </div>
                    <div className="flex items-center justify-between rounded-2xl bg-white px-4 py-3">
                      <span>Low</span>
                      <span>{distribution.low} mechanism{distribution.low > 1 ? 's' : ''}</span>
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-4">
                  <p className="text-sm font-semibold text-slate-900">Deployment chart</p>
                  <div className="mt-4 flex items-center justify-center">
                    <div className="relative flex h-40 w-40 items-center justify-center rounded-full bg-slate-100">
                      <div className="absolute inset-0 rounded-full bg-gradient-to-r from-blue-500 to-emerald-500" style={{ clipPath: `polygon(50% 0%, 100% 0, 100% 100%, 0 100%, 0 0, 50% 0)` }} />
                      <div className="relative flex h-28 w-28 items-center justify-center rounded-full bg-white text-center">
                        <div>
                          <p className="text-2xl font-semibold text-slate-900">{(averageDeployment * 100)?.toFixed(0)}%</p>
                          <p className="text-xs text-slate-500">Average deployment</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-white p-5 text-sm text-slate-700">
                  <p className="font-semibold text-slate-900">Help & explanation</p>
                  <ul className="mt-4 list-disc space-y-2 pl-5">
                    <li>Enable only the mechanisms relevant to your scenario.</li>
                    <li>The deployment level represents implementation intensity.</li>
                    <li>A value near 1 indicates full deployment.</li>
                    <li>A value near 0 means the mechanism is lightly or not applied.</li>
                  </ul>
                </div>

                <div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">
                  <p className="font-semibold">Important</p>
                  <p className="mt-2">You can adjust these settings after reviewing the impact matrix on the next step.</p>
                </div>
              </aside>
            </div>
          </div>
        )}

        {currentStep === 2 && (
          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">Impact matrix</h2>
              <p className="text-gray-600 mt-1">Define how each mechanism affects each risk indicator.</p>
            </div>

            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-6">
              <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                <div>
                  <p className="text-sm font-semibold text-slate-900">Mechanism → Indicator matrix</p>
                  <p className="text-sm text-slate-500">Adjust the impact coefficients to refine the central calculation.</p>
                </div>
                <div className="flex flex-wrap items-center gap-3">
                  <button
                    type="button"
                    onClick={resetMatrix}
                    disabled={isReadOnly}
                    className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-100"
                  >
                    Reset matrix
                  </button>
                  <button
                    type="button"
                    className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-100"
                  >
                    Import template
                  </button>
                  <button
                    type="button"
                    className="rounded-2xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-blue-700"
                  >
                    Save matrix
                  </button>
                </div>
              </div>
            </div>

            <div className="grid gap-6 xl:grid-cols-[2fr_1.1fr]">
              <div className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6">
                <div className="overflow-x-auto pb-2">
                  <table className="w-full table-auto border-separate border-spacing-0 text-sm text-slate-700">
                    <thead>
                      <tr>
                        <th className="sticky left-0 z-10 bg-white px-3 py-2 text-left font-semibold text-slate-900 shadow-sm">Mechanism</th>
                        {apiIndicators.map((indicatorObj) => { 
                          const indicator = indicatorObj.name; 
                          return (
                          <th key={indicator} className="whitespace-normal break-words px-3 py-2 text-left font-semibold text-slate-900 max-w-[10rem]">
                            {indicator}
                          </th>
                        )})}
                      </tr>
                    </thead>
                    <tbody>
                      {mechanisms.map((mechanism) => (
                        <tr key={mechanism.id} className="border-t border-slate-200">
                          <td className="sticky left-0 z-10 bg-white px-3 py-3">
                            <div className="flex flex-col gap-2">
                              <div className="flex items-start justify-between gap-3">
                                <div className="min-w-0">
                                  <p className="font-semibold text-slate-900">{mechanism.name}</p>
                                  <p className="text-xs text-slate-500">{mechanism.description}</p>
                                </div>
                                <label className="inline-flex cursor-pointer items-center gap-2 text-xs font-medium text-slate-700">
                                  <input
                                    type="checkbox"
                                    checked={mechanism.active}
                                    onChange={(e) => updateMechanism(mechanism.id, { active: e.target.checked })}
                                    disabled={isReadOnly}
                                    className="h-5 w-5 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                                  />
                                  Active
                                </label>
                              </div>
                            </div>
                          </td>
                          {apiIndicators.map((indicatorObj) => { 
                            const indicator = indicatorObj.name; 
                            const value = mechanism.effects[indicator] ?? 0;
                            return (
                              <td key={indicator} className="px-2 py-2 text-center">
                                <button
                                  type="button"
                                  onClick={() => !isReadOnly && setEditingCell({ rmmId: mechanism.id, indicator })}
                                  disabled={isReadOnly}
                                  className={`mx-auto inline-flex min-w-[3rem] items-center justify-center rounded-xl px-2 py-1 text-xs font-semibold transition ${getCellClasses(value)}`}
                                >
                                  {value >= 0 ? '+' : ''}{value?.toFixed(1)}
                                </button>
                              </td>
                            );
                          })}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {editingCell && (
                  <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                      <div>
                        <p className="text-sm font-semibold text-slate-900">Edit impact</p>
                        <p className="text-sm text-slate-500">
                          {mechanisms.find((item) => item.id === editingCell.rmmId)?.name} → {editingCell.indicator}
                        </p>
                      </div>
                      <button
                        type="button"
                        onClick={() => setEditingCell(null)}
                        className="rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-100"
                      >
                        Close
                      </button>
                    </div>
                    <div className="mt-5 space-y-4">
                      <input
                        type="range"
                        min={-1}
                        max={1}
                        step={0.05}
                        value={mechanisms.find((item) => item.id === editingCell.rmmId)?.effects[editingCell.indicator] ?? 0}
                        onChange={(e) => updateMechanismEffect(editingCell.rmmId, editingCell.indicator, Number(e.target.value))}
                        className="w-full accent-blue-600"
                      />
                      <div className="flex items-center gap-4">
                        <span className="text-sm text-slate-500">-1 = negative impact</span>
                        <span className="text-sm text-slate-500">0 = neutral</span>
                        <span className="text-sm text-slate-500">+1 = strong impact</span>
                      </div>
                      <div className="grid gap-4 sm:grid-cols-2">
                        <label className="space-y-2 text-sm text-slate-700">
                          Exact value
                          <input
                            type="number"
                            min={-1}
                            max={1}
                            step={0.05}
                            value={mechanisms.find((item) => item.id === editingCell.rmmId)?.effects[editingCell.indicator] ?? 0}
                            onChange={(e) => updateMechanismEffect(editingCell.rmmId, editingCell.indicator, Number(e.target.value))}
                            className="w-full rounded-2xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-blue-500"
                          />
                        </label>
                        <div className="rounded-3xl bg-white px-4 py-3 text-sm text-slate-700 shadow-sm">
                          <p className="font-semibold text-slate-900">Interpretation</p>
                          <p className="mt-2">
                            {editingCell.indicator} will be adjusted according to the selected level. The higher the value, the more the risk is reduced.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-700">
                  <p className="font-semibold text-slate-900">Legend</p>
                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    <div className="rounded-2xl bg-emerald-500 px-3 py-3 text-white">Strong impact (+0.7 to +1)</div>
                    <div className="rounded-2xl bg-emerald-200 px-3 py-3 text-slate-900">Moderate impact (+0.3 to +0.7)</div>
                    <div className="rounded-2xl bg-emerald-100 px-3 py-3 text-slate-900">Low impact (+0.0 to +0.3)</div>
                    <div className="rounded-2xl bg-slate-100 px-3 py-3 text-slate-700">Neutral (0)</div>
                    <div className="rounded-2xl bg-red-100 px-3 py-3 text-red-700">Negative impact (-1 to -0.1)</div>
                  </div>
                </div>
              </div>

              <aside className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <div>
                  <p className="text-sm font-semibold text-slate-900">Matrix summary</p>
                  <div className="mt-5 space-y-4 text-sm text-slate-700">
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Active mechanisms</p>
                      <p className="mt-2 text-3xl font-semibold text-blue-600">{activeCount} / {mechanisms.length}</p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Indicators impacted</p>
                      <p className="mt-2 text-3xl font-semibold text-blue-600">{impactedIndicatorsCount} / {apiIndicators.length}</p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Average impact</p>
                      <p className="mt-2 text-3xl font-semibold text-emerald-700">{matrixAverageImpact?.toFixed(2)}</p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 px-4 py-4">
                      <p className="font-semibold text-slate-900">Max / min impact</p>
                      <p className="mt-2 text-3xl font-semibold text-slate-900">{matrixMaxImpact?.toFixed(2)} / {matrixMinImpact?.toFixed(2)}</p>
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-4">
                  <p className="text-sm font-semibold text-slate-900">Impact distribution</p>
                  <div className="mt-4 flex items-center justify-between gap-4">
                    <div className="flex h-24 w-24 items-center justify-center rounded-full bg-slate-100 text-center">
                      <div>
                        <p className="text-2xl font-semibold text-slate-900">{allActiveCellValues.length}</p>
                        <p className="text-xs text-slate-500">Impacts</p>
                      </div>
                    </div>
                    <div className="flex-1 space-y-3 text-sm text-slate-700">
                      <div className="flex items-center justify-between rounded-2xl bg-white px-3 py-2">
                        <span>Strong impact</span>
                        <span>{matrixDistribution.strong} ({allActiveCellValues.length ? Math.round((matrixDistribution.strong / allActiveCellValues.length) * 100) : 0}%)</span>
                      </div>
                      <div className="flex items-center justify-between rounded-2xl bg-white px-3 py-2">
                        <span>Moderate impact</span>
                        <span>{matrixDistribution.moderate} ({allActiveCellValues.length ? Math.round((matrixDistribution.moderate / allActiveCellValues.length) * 100) : 0}%)</span>
                      </div>
                      <div className="flex items-center justify-between rounded-2xl bg-white px-3 py-2">
                        <span>Low impact</span>
                        <span>{matrixDistribution.weak} ({allActiveCellValues.length ? Math.round((matrixDistribution.weak / allActiveCellValues.length) * 100) : 0}%)</span>
                      </div>
                      <div className="flex items-center justify-between rounded-2xl bg-white px-3 py-2">
                        <span>Neutral</span>
                        <span>{matrixDistribution.neutral} ({allActiveCellValues.length ? Math.round((matrixDistribution.neutral / allActiveCellValues.length) * 100) : 0}%)</span>
                      </div>
                      <div className="flex items-center justify-between rounded-2xl bg-white px-3 py-2">
                        <span>Negative impact</span>
                        <span>{matrixDistribution.negative} ({allActiveCellValues.length ? Math.round((matrixDistribution.negative / allActiveCellValues.length) * 100) : 0}%)</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-700">
                  <p className="font-semibold text-slate-900">Understanding the matrix</p>
                  <ul className="mt-4 list-disc space-y-2 pl-5">
                    <li>Each cell represents the effect of a mechanism on an indicator.</li>
                    <li>Positive values indicate expected risk reduction.</li>
                    <li>Negative values indicate a possible perverse effect.</li>
                    <li>0 means no impact is expected.</li>
                  </ul>
                </div>

                <div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">
                  <p className="font-semibold">Important</p>
                  <p className="mt-2">Too high impacts can bias the results. Base your values on real data.</p>
                </div>
              </aside>
            </div>
          </div>
        )}

        {currentStep === 3 && (
          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">Results & comparison</h2>
              <p className="text-gray-600 mt-1">Analyze your simulation results and compare different scenarios.</p>
            </div>

            <div className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
              <div className="grid gap-6 xl:grid-cols-2">
                <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <p className="text-sm font-semibold text-slate-900">Risk score before simulation</p>
                  <div className="mt-4 flex items-center justify-between gap-4">
                    <div>
                      <p className="text-3xl font-semibold text-slate-900">{riskScoreInitial?.toFixed(2)}</p>
                      <p className="text-sm text-slate-500">Risk level: High</p>
                    </div>
                    <div className="h-2 flex-1 rounded-full bg-red-100">
                      <div className="h-full w-[78%] rounded-full bg-red-600" />
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <p className="text-sm font-semibold text-slate-900">Risk score after simulation</p>
                  <div className="mt-4 flex items-center justify-between gap-4">
                    <div>
                      <p className="text-3xl font-semibold text-slate-900">{riskScoreAfter?.toFixed(2)}</p>
                      <p className="text-sm text-slate-500">Risk level: {riskLevelLabel(riskScoreAfter) === 'HIGH' ? 'High' : riskLevelLabel(riskScoreAfter) === 'MODERATE' ? 'Moderate' : 'Low'}</p>
                    </div>
                    <div className="h-2 flex-1 rounded-full bg-amber-100">
                      <div className="h-full w-[52%] rounded-full bg-amber-600" />
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-2">
                <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <p className="text-sm font-semibold text-slate-900">Overall impact</p>
                  <div className="mt-5 flex items-center justify-between gap-4">
                    <div>
                      <p className="text-3xl font-semibold text-emerald-700">{reductionAbsolute?.toFixed(2)}</p>
                      <p className="text-sm text-slate-500">Absolute risk score reduction</p>
                    </div>
                    <div className="rounded-3xl bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-700">{reductionRelative}%</div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <p className="text-sm font-semibold text-slate-900">Result confidence</p>
                  <div className="mt-5 space-y-4">
                    <div>
                      <p className="text-3xl font-semibold text-slate-900">65%</p>
                      <p className="text-sm text-slate-500">Based on current parameters and data</p>
                    </div>
                    <div className="inline-flex rounded-3xl bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700">
                      Average
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="grid gap-6 xl:grid-cols-4">
              <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Improved indicators</p>
                <p className="mt-4 text-3xl font-semibold text-blue-600">{impactCounts.improved}</p>
                <p className="text-sm text-slate-500">Out of {apiIndicators.length} indicators</p>
              </div>
              <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Stable indicators</p>
                <p className="mt-4 text-3xl font-semibold text-slate-900">{impactCounts.stable}</p>
                <p className="text-sm text-slate-500">Out of {apiIndicators.length} indicators</p>
              </div>
              <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Degraded indicators</p>
                <p className="mt-4 text-3xl font-semibold text-red-600">{impactCounts.degraded}</p>
                <p className="text-sm text-slate-500">Out of {apiIndicators.length} indicators</p>
              </div>
              <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
                <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Max observed impact</p>
                <p className="mt-4 text-3xl font-semibold text-emerald-700">-{Math.max(...indicatorImpactData.map((item) => item.value))}%</p>
                <p className="text-sm text-slate-500">On error rate</p>
              </div>
            </div>

            <div className="grid gap-6 xl:grid-cols-[1.4fr_0.9fr_0.9fr]">
              <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Risk score trend over time</p>
                    <p className="text-sm text-slate-500">Current situation vs after simulation.</p>
                  </div>
                  <span className="text-xs text-slate-500">T0 → T+3</span>
                </div>
                <div className="mt-6 rounded-3xl bg-slate-50 p-5">
                  <div className="relative h-52">
                    <svg viewBox="0 0 520 240" className="h-full w-full">
                      <path d="M40 30 L40 210 L500 210" stroke="#CBD5E1" strokeWidth="1" fill="none" />
                      <path d={actualRiskTrendPath} stroke="#4338CA" strokeWidth="3" fill="none" strokeLinecap="round" />
                      <path d={afterRiskTrendPath} stroke="#2563EB" strokeWidth="2" fill="none" strokeDasharray="8 6" strokeLinecap="round" />
                      {actualRiskTrend.map((point, index) => {
                        const x = 40 + index * 120;
                        const y = 210 - ((point.value - riskTrendMin) / riskTrendRange) * 150;
                        return (
                          <g key={`actual-${point.label}`}>
                            <circle cx={x} cy={y} r={5} fill="#4338CA" />
                            <text x={x} y={y - 12} textAnchor="middle" className="text-[11px] font-semibold" fill="#1F2937">
                              {point.value?.toFixed(2)}
                            </text>
                            <text x={x} y={230} textAnchor="middle" className="text-[11px] fill-[#6B7280]">
                              {point.label}
                            </text>
                          </g>
                        );
                      })}
                      {afterRiskTrend.map((point, index) => {
                        const x = 40 + index * 120;
                        const y = 210 - ((point.value - riskTrendMin) / riskTrendRange) * 150;
                        return <circle key={`after-${point.label}`} cx={x} cy={y} r={4} fill="#2563EB" />;
                      })}
                    </svg>
                  </div>
                  <div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-slate-500">
                    <div className="flex items-center gap-2">
                      <span className="h-2.5 w-2.5 rounded-full bg-[#4338CA] block" />
                      Current situation
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="inline-block h-0.5 w-6 rounded-full bg-[#2563EB]" />
                      After simulation
                    </div>
                  </div>
                </div>
              </div>

              <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Indicator impact</p>
                    <p className="text-sm text-slate-500">Estimated reduction by criterion.</p>
                  </div>
                </div>
                <div className="mt-6 space-y-4">
                  {indicatorImpactData.map((item) => (
                    <div key={item.indicator} className="space-y-2">
                      <div className="flex items-center justify-between text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
                        <span>{item.indicator}</span>
                        <span>-{item.value}%</span>
                      </div>
                      <div className="h-3 w-full overflow-hidden rounded-full bg-slate-100">
                        <div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.min(100, Math.max(0, item.value))}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Mechanism contributions</p>
                    <p className="text-sm text-slate-500">Overall mitigation impact.</p>
                  </div>
                </div>
                <div className="mt-6 space-y-4">
                  {contributionData.map((item) => (
                    <div key={item.name} className="space-y-2">
                      <div className="flex items-center justify-between text-sm text-slate-700">
                        <span>{item.name}</span>
                        <span className="font-semibold text-slate-900">{item.value}%</span>
                      </div>
                      <div className="h-3 w-full overflow-hidden rounded-full bg-slate-100">
                        <div className="h-full rounded-full bg-blue-600" style={{ width: `${item.value}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="grid gap-6 xl:grid-cols-[1.7fr_0.8fr]">
              <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">Scenario comparison</p>
                    <p className="text-sm text-slate-500">Find the best-performing scenario.</p>
                  </div>
                </div>
                <div className="mt-6 overflow-x-auto">
                  <table className="min-w-full text-left text-sm text-slate-700">
                    <thead>
                      <tr>
                        <th className="pb-3 font-semibold text-slate-900">Scenario</th>
                        <th className="pb-3 font-semibold text-slate-900">Initial risk score</th>
                        <th className="pb-3 font-semibold text-slate-900">Post-risk score</th>
                        <th className="pb-3 font-semibold text-slate-900">Reduction</th>
                        <th className="pb-3 font-semibold text-slate-900">Level</th>
                        <th className="pb-3 font-semibold text-slate-900">Confidence</th>
                      </tr>
                    </thead>
                    <tbody>
                      {scenarioComparisonData.map((scenario) => (
                        <tr key={scenario.name} className={scenario.best ? 'bg-blue-50' : 'bg-white'}>
                          <td className="py-4 pr-4">
                            <div className="flex items-center gap-2">
                              {scenario.best && <span className="inline-flex h-6 items-center rounded-full bg-blue-600 px-2.5 text-[10px] font-semibold uppercase tracking-[0.18em] text-white">Best</span>}
                              <span className="font-semibold text-slate-900">{scenario.name}</span>
                            </div>
                          </td>
                          <td className="py-4 pr-4 text-slate-500">{scenario.initial?.toFixed(2)}</td>
                          <td className="py-4 pr-4 text-slate-900">{scenario.after?.toFixed(2)}</td>
                          <td className="py-4 pr-4 text-slate-900">-{scenario.reduction}%</td>
                          <td className="py-4 pr-4">
                            <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${scenario.level === 'LOW' ? 'bg-emerald-100 text-emerald-700' : scenario.level === 'MODERATE' ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-700'}`}>
                              {scenario.level}
                            </span>
                          </td>
                          <td className="py-4 text-slate-500">{scenario.confidence}%</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <aside className="space-y-6">
                <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <p className="text-sm font-semibold text-slate-900">Analysis & recommendations</p>
                  <div className="mt-4 space-y-3 text-sm text-slate-700">
                    <p>The scenario <strong>{scenarioComparisonData.find((scenario) => scenario.best)?.name}</strong> offers the best risk reduction.</p>
                    <p>The mechanisms Regular algorithmic audit and Technical data improvements are the main drivers of performance.</p>
                    <p>No key indicator is degraded in this scenario, which reinforces its relevance.</p>
                    <p>Reassess the strategy after each mechanism change to refine decision-making.</p>
                  </div>
                </div>

                {!isReadOnly && <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <p className="text-sm font-semibold text-slate-900">Actions</p>
                  <div className="mt-4 space-y-3">
                    <button onClick={() => { alert('Your results have been successfully saved to the database! You can find them on your dashboard.'); window.location.reload(); }} className="w-full rounded-2xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-700">Save results</button>
                    <button onClick={exportPDF} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-900 hover:bg-slate-100">Export (PDF)</button>
                    <button onClick={exportCSV} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-900 hover:bg-slate-100">Export (CSV)</button>
                    <button className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-900 hover:bg-slate-100">Compare with another scenario</button>
                  </div>
                </div>}
              </aside>
            </div>
          </div>
        )}

        <div className="mt-8 flex flex-col gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={goBack}
              disabled={currentStep === 0}
              className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 transition hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Back
            </button>
            {currentStep < steps.length - 1 && (
            <button
              type="button"
              onClick={goNext}
              className="rounded-2xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-blue-700"
            >
              {currentStep === 0
                ? 'Next: Simulation'
                : currentStep === 1
                ? 'Next: Impact matrix'
                : 'Run simulation'}
            </button>
            )}
          </div>
          <p className="text-sm text-slate-500">Step {currentStep + 1} of {steps.length}</p>
        </div>
      </div>

      {/* ── Create Scenario Modal ── */}
      {showCreateScenario && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
          <div className="w-full max-w-lg rounded-3xl border border-slate-200 bg-white p-8 shadow-xl">
            <div className="mb-6">
              <h3 className="text-lg font-semibold text-slate-900">Create a new scenario</h3>
              <p className="text-sm text-slate-500 mt-1">Define a new mitigation scenario for your simulations.</p>
            </div>
            <div className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-slate-700">Scenario name <span className="text-red-500">*</span></label>
                <input
                  type="text"
                  value={newScenarioName}
                  onChange={(e) => setNewScenarioName(e.target.value)}
                  placeholder="e.g. Advanced technical strengthening"
                  className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
                  autoFocus
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700">Description</label>
                <textarea
                  value={newScenarioDesc}
                  onChange={(e) => setNewScenarioDesc(e.target.value)}
                  placeholder="Describe the strategy and objectives of this scenario..."
                  rows={3}
                  className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100 resize-none"
                />
              </div>
            </div>
            <div className="mt-8 flex items-center justify-end gap-3">
              <button
                type="button"
                onClick={() => { setShowCreateScenario(false); setNewScenarioName(''); setNewScenarioDesc(''); }}
                className="rounded-2xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-100"
                disabled={creatingScenario}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleCreateScenario}
                disabled={!newScenarioName.trim() || creatingScenario}
                className="rounded-2xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {creatingScenario ? 'Creating…' : 'Create scenario'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
